<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VNNOT01519" failures="8" tests="14" name="Login Test with Chrome browser" time="47.025" errors="0" timestamp="2025-06-26T15:45:34 GMT+07:00">
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProviderHashTable" time="3.134">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProviderHashTable -->
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccess" time="3.806">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccess(LoginTest.java:42)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccess -->
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProvider" time="5.174"/>
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProviderHashTable" time="3.753">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProviderHashTable -->
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginFailWithEmailInvalid" time="4.575"/>
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProvider" time="2.832">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginFailWithPasswordInvalid" time="4.021"/>
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProviderHashTable" time="7.613">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProviderHashTable -->
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProvider" time="3.607">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginFailWithEmailNull" time="3.929"/>
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginFailWithPasswordNull" time="3.394"/>
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProvider" time="3.067">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginFailWithEmailNullAndPasswordNull" time="2.309"/>
  <testcase classname="com.anhtester.Bai34_AllureReport_testcases.LoginTest" name="loginSuccessFromDataProvider" time="2.584">
    <failure type="java.lang.AssertionError" message="FAIL Because Still in the Login page: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessFromDataProvider -->
</testsuite> <!-- Login Test with Chrome browser -->
